---
collections:

- name: ansible.posix
  version: 2.1.0

- name: community.general
  version: 12.3.0

- name: community.docker
  version: 5.0.6

- name: devsec.hardening
  version: 10.5.0

roles:

- src: geerlingguy.ntp
  version: "4.0.0"

- src: andrewrothstein.miniconda
  version: "v6.1.9"

- src: nvidia.nvidia_driver
  version: "v2.3.1"

- src: nvidia.nvidia_docker
  version: "v1.2.4"

- src: nvidia.enroot
  version: "v0.5.0"

- src: gantsign.golang
  version: 3.5.0
