#!/usr/bin/env bash
set -ex

tmpfs_mounted="$(findmnt /tmp | grep ' tmpfs ' | cat)"
tmpfs_infstab="$(grep '/tmp ' /etc/fstab | grep ' tmpfs ' | cat)"

# Cleanup /tmp
if [ ! -z "$tmpfs_mounted" ] && [ ! -z "$tmpfs_infstab" ]; then
    umount /tmp
    mount /tmp
else
    rm -rf /tmp/*
fi

# Cleanup /dev/shm
rm -rf /dev/shm/*

# Cleanup caches
sync
echo 3 > /proc/sys/vm/drop_caches
