---
## This example configures the IB interfaces used by the K8s cluster.
##
- name: Create sriov network definition
  vars:
    spec_yaml: |
      resourceName: "{{ item.res_name }}"
      linkState: "enable"
      networkNamespace: "default"
      ipam: |
        {
          "type": "{{ nvidia_network_operator_ipam_type }}",
          "poolName": "{{ item.ip_pool_name | default(item.res_name) }}"
        }
  k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovIBNetwork
      metadata:
        name: "{{ item.if_name }}"
        namespace: network-operator
      spec: "{{ spec_yaml | from_yaml }}"
  run_once: true
