#!/usr/bin/env bash
set -ex

numcpus_sys=$(( $(grep -c ^processor /proc/cpuinfo) * $(scontrol show job "$SLURM_JOBID" | grep -Eio "TRES=.*node=[0-9]+" | cut -d= -f5) ))
numcpus_job=$(scontrol show job "$SLURM_JOBID" | grep -Eio "TRES=cpu=[0-9]+" | cut -d= -f3)
if [ "$numcpus_sys" == "$numcpus_job" ] ; then
    logger -s -t slurm-prolog 'running prolog tasks for exclusive job'
    run-parts /etc/slurm/prolog-exclusive.d
else
    logger -s -t slurm-prolog "skipping exclusive prolog tasks - $numcpus_sys, $numcpus_job"
fi
