#!/usr/bin/env bash

# Add user to Docker group
usermod -aG docker "$SLURM_JOB_USER"

# Set up subuid/subgid for rootless LXC support
uid=$(id -u "$SLURM_JOB_USER")
gid=$(id -g "$SLURM_JOB_USER")
echo "${uid}:165536:65536" >> /etc/subuid
echo "${gid}:165536:65536" >> /etc/subgid

# Allow user to SSH to machine if exclusive
numcpus_sys=$(grep -c ^processor /proc/cpuinfo)
numcpus_job=$(scontrol show job "$SLURM_JOBID" | grep -Eio "TRES=cpu=[0-9]+" | cut -d= -f3)
if [ "$numcpus_sys" == "$numcpus_job" ] ; then
    echo "$SLURM_JOB_USER" >> /etc/localusers
fi

## Performance settings
# MAX-P
if [ "$SLURM_JOB_PARTITION" == "maxp" ] ; then
    # Set CPU frequency to performance governor
    cpupower frequency-set -g performance
    /etc/slurm/shared/bin/set_gpu_power_levels.sh max
# MAX-Q
elif [ "$SLURM_JOB_PARTITION" == "maxq" ] ; then
    # Set CPU frequency to powersave governor
    cpupower frequency-set -g powersave
    /etc/slurm/shared/bin/set_gpu_power_levels.sh min
# batch (temporary - need to consider settings for default queue)
else
    cpupower frequency-set -g performance
    /etc/slurm/shared/bin/set_gpu_power_levels.sh max
fi
