#!/usr/bin/env bash

# Add user to Docker group
usermod -aG docker "${SLURM_JOB_USER}"

# Set up subuid/subgid for rootless LXC support
uid=$(id -u ${SLURM_JOB_USER})
gid=$(id -g ${SLURM_JOB_USER})
echo "${uid}:165536:65536" >> /etc/subuid
echo "${gid}:165536:65536" >> /etc/subgid

# Allow user to SSH to machine if exclusive
numcpus_sys=$(cat /proc/cpuinfo | grep ^processor | wc -l)
numcpus_job=$(scontrol show job ${SLURM_JOBID} | egrep -io "TRES=cpu=[0-9]+" | cut -d= -f3)
if [ "${numcpus_sys}" == "${numcpus_job}" ] ; then
    echo "${SLURM_JOB_USER}" >> /etc/localusers
fi

## Performance settings
# MAX-P
if [ "${SLURM_JOB_PARTITION}" == "maxp" ] ; then
    # Set CPU frequency to performance governor
    cpupower frequency-set -g performance
    nvidia-smi -pl 300
# MAX-Q
elif [ "${SLURM_JOB_PARTITION}" == "maxq" ] ; then
    # Set CPU frequency to powersave governor
    cpupower frequency-set -g powersave
    nvidia-smi -pl 180
# batch (temporary - need to consider settings for default queue)
else
    cpupower frequency-set -g performance
    nvidia-smi -pl 300
fi
