VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE = "generic/ubuntu1804"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "mgmt" do |mgmt|
    mgmt.vm.provider "libvirt" do |v|
      v.memory = 2048
    end
    mgmt.vm.box = BOX_IMAGE
    mgmt.vm.hostname = "mgmt"
    mgmt.vm.network :private_network, ip: "10.0.0.2"
  end

  config.vm.define "login01" do |login|
    login.vm.box = BOX_IMAGE
    login.vm.hostname = "login01"
    login.vm.network :private_network, ip: "10.0.0.4"
  end

  config.vm.define "dgx01" do |dgx|
    config.vm.provider "libvirt" do |v|
      v.memory = 16384
      v.cpus = 2
      v.machine_type = "q35"
      v.cpu_mode = "host-passthrough"
      # comment in for pci passthrough (and change bus according
      # to local hw setup - `lspci -nnk | grep NVIDIA`)
      v.pci :bus => '0x08', :slot => '0x00', :function => '0x0'
    end
    dgx.vm.box = BOX_IMAGE
    dgx.vm.hostname = "dgx01"
    dgx.vm.network :private_network, ip: "10.0.0.11"
  end
end
