---
- name: Include Red Hat DGX variables
  include_vars: redhat.yml

- name: Check for supported Red Hat family DGX Software Stack version
  fail:
    msg: "Role supports Red Hat family major versions 7, 8, and 9 only"
  when: ansible_distribution_major_version not in ['7', '8', '9']

- name: Run legacy EL7 DGX tasks
  include_tasks: redhat-legacy-el7.yml
  when: ansible_distribution_major_version == '7'

- name: Run EL8 and EL9 DGX Software Stack tasks
  include_tasks: redhat-el8-plus.yml
  when: ansible_distribution_major_version in ['8', '9']
