---
- name: Check for supported Ubuntu DGX Software Stack version
  fail:
    msg: "Role supports Ubuntu 18.04, 20.04, 22.04, and 24.04 only"
  when: ansible_distribution_version not in ['18.04', '20.04', '22.04', '24.04']

- name: Run legacy DGX OS 4/5 tasks
  include_tasks: ubuntu-legacy.yml
  when: ansible_distribution_version in ['18.04', '20.04']

- name: Run DGX OS 6 tasks
  include_tasks: ubuntu-22.04.yml
  when: ansible_distribution_version == '22.04'

- name: Run DGX OS 7 tasks
  include_tasks: ubuntu-24.04.yml
  when: ansible_distribution_version == '24.04'
