#!/bin/sh

## CONFIG
MNT=${MNT:-/data}
ISO=${ISO:-/iso}
PRESEED=${ISO}/preseed/pxe.template.seed
INT=${INT:-enp1s0f0}
DISK=${DISK:-sda}
DEFAULT=${DEFAULT:-local}
HTTP_PORT=${HTTP_PORT:-13370}
KBD=${KBD:-us}
KERN_EXTRA=${KERN_EXTRA:-}
HOST_INT_PUB=${HOST_INT_PUB:-eth0}
HOST_INT_PRV=${HOST_INT_PRV:-eth1}
NETWORK=${NETWORK:-192.168.1.0}
NETMASK=${NETMASK:-255.255.255.0}
IP=${IP:-192.168.1.1}
GATEWAY=${GATEWAY:-${IP}}
DNS1=${DNS1:-8.8.8.8}
DNS2=${DNS2:-8.8.4.4}
DHCP_START=${DHCP_START:-192.168.1.100}
DHCP_END=${DHCP_END:-192.168.1.199}
LEASETIME=${LEASETIME:-7200}
DOMAIN=${DOMAIN:-local}
HTTPS_PROXY=${HTTPS_PROXY:-}
EXTRA_PACKAGES=${EXTRA_PACKAGES:-}
MY_POD_NAME=${MY_POD_NAME:-}
NUM_OF_REPLICAS=${NUM_OF_REPLICAS:-1}
###

iptoi()
{
  a=$(echo "${1}" | cut -d"." -f1)
  b=$(echo "${1}" | cut -d"." -f2)
  c=$(echo "${1}" | cut -d"." -f3)
  d=$(echo "${1}" | cut -d"." -f4)

  echo "$(((a<<24)+(b<<16)+(c<<8)+d))"
}

itoip()
{
  #returns the dotted-decimal ascii form of an IP arg passed in integer format
  echo -n $(($(($(($((${1}/256))/256))/256))%256)).
  echo -n $(($(($((${1}/256))/256))%256)).
  echo -n $(($((${1}/256))%256)).
  echo $((${1}%256))
}

SHARD_IDX=$(( ${MY_POD_NAME##*-} ))

if [ "${NUM_OF_REPLICAS}" -gt 1 ]; then
  STARTINT=$(iptoi ${DHCP_START})
  ENDINT=$(iptoi ${DHCP_END})

  IPCOUNT=$(( ${ENDINT} - ${STARTINT} + 1 ))

  SHARDIPCOUNT=$(( ${IPCOUNT} / ${NUM_OF_REPLICAS} ))

  DHCP_START=$(itoip $(( STARTINT + (SHARD_IDX * SHARDIPCOUNT) )))
  DHCP_END=$(itoip $(( STARTINT + ((SHARD_IDX + 1) * (SHARDIPCOUNT) - 1) )))
fi

mkdir -p "${ISO}"

# Check for mounted DGX Server ISO
find ${PRESEED} >/dev/null 2>&1
if [ $? -ne 0 ] ; then
    dgx_iso="$(find ${MNT} -name DGXServer\*.iso)"
    mount -o loop -t iso9660 "$dgx_iso" "${ISO}"
fi

# Check for mounted DGX Server ISO
find ${PRESEED} >/dev/null 2>&1
if [ $? -eq 0 ] ; then
	cp ${PRESEED} /www/dgx.seed
	PRESEED=/www/dgx.seed
	ln -sf ${ISO} /www/iso

    # Modify preseed
    sed -i "s/^d-i live-installer.*/d-i live-installer\/net-image string ftp:\/\/${IP}\/install\/filesystem.squashfs/g" ${PRESEED}
    sed -i "s/^d-i mirror\/ftp\/hostname.*/d-i mirror\/ftp\/hostname string ${IP}/g" ${PRESEED}
    sed -i "s/^d-i apt-setup\/local0\/repository.*/d-i apt-setup\/local0\/repository string deb ftp:\/\/${IP}\/ xenial main multiverse/g" ${PRESEED}
    sed -i "s/^d-i mirror\/ftp\/directory.*/d-i mirror\/ftp\/directory string \//g" ${PRESEED}
    sed -i "s/^d-i apt-setup\/security_host.*/d-i apt-setup\/security_host string ${IP}/g" ${PRESEED}

    # Try to get install process to fix BIOS boot order on pre-3.18 BMC firmwares; sets DGX to boot from first disk
    # Turn off chassis identify light
    sed -i "s/in-target sh -c \"logger preseed\/late_command: end\"\;/modprobe -v ipmi_devintf\; \\\\\n\\t in-target sh -c \"sudo ipmitool raw 0x00 0x08 0x05 0xe0 0x08 0x00 0x00 0x00\"\; \\\\\n\\t in-target sh -c \"sudo ipmitool chassis identify 0\"\; \\\\\n\\t in-target sh -c \"curl -X POST -d action=end ${IP}:${HTTP_PORT}\/install\"\; \\\\\n\\tin-target sh -c \"logger preseed\/late_command: end\"\;/g" ${PRESEED}
    sed -i "s~^d-i mirror/https/proxy.*~d-i mirror/https/proxy string ${HTTPS_PROXY}~g" ${PRESEED}
    sed -i "s~^d-i pkgsel/include string ~d-i pkgsel/include string ${EXTRA_PACKAGES} ~g" ${PRESEED}

    # Add early command to log install start
    #sed -i "s/^# Use default/d-i preseed\/early_command string wget --post-data action=start ${IP}\/install\\n\\n# Use default/g" ${PRESEED}
    #sed -i "s/early_command string/early_command string wget --post-data action=start 192.168.1.1\/install \;/g" ${PRESEED}

    # Useful for Xen VM
    sed -i "s/\/dev\/sda/\/dev\/${DISK}/g" ${PRESEED}
    sed -i "s/enp1s0f0/${INT}/g" ${PRESEED}

    # FTP
    sed -i "s~/srv/ftp~${ISO}~g" /etc/passwd

else
	echo "DGX ISO must be mounted at ${ISO}"
	echo "can't find ${PRESEED}"
fi

# DHCP
sed -i "s/\#HOST_INT_PRV\#/${HOST_INT_PRV}/g" /etc/dnsmasq.conf
sed -i "s/\#LEASETIME\#/${LEASETIME}/g" /etc/dnsmasq.conf
sed -i "s/\#DOMAIN\#/${DOMAIN}/g" /etc/dnsmasq.conf
sed -i "s/\#IP\#/${IP}/g" /etc/dnsmasq.conf
sed -i "s/\#NETWORK\#/${NETWORK}/g" /etc/dnsmasq.conf
sed -i "s/\#NETMASK\#/${NETMASK}/g" /etc/dnsmasq.conf
sed -i "s/\#GATEWAY\#/${GATEWAY}/g" /etc/dnsmasq.conf
sed -i "s/\#DNS1\#/${DNS1}/g" /etc/dnsmasq.conf
sed -i "s/\#DNS2\#/${DNS2}/g" /etc/dnsmasq.conf
sed -i "s/\#DHCP_START\#/${DHCP_START}/g" /etc/dnsmasq.conf
sed -i "s/\#DHCP_END\#/${DHCP_END}/g" /etc/dnsmasq.conf

# HTTP
sed -i "s/\#HTTP_PORT\#/${HTTP_PORT}/g" /etc/nginx/nginx.conf

if [ ! -z "${HOST_INT_PUB}" ]; then
  # NAT
  /sbin/iptables -t nat -A POSTROUTING -o ${HOST_INT_PUB} -j MASQUERADE
  /sbin/iptables -A FORWARD -i ${HOST_INT_PUB} -o ${HOST_INT_PRV} -m state --state RELATED,ESTABLISHED -j ACCEPT
  /sbin/iptables -A FORWARD -i ${HOST_INT_PRV} -o ${HOST_INT_PUB} -j ACCEPT
  sysctl -w net.ipv4.ip_forward=1
fi

# Run some servers
nginx &
/usr/sbin/vsftpd /etc/vsftpd.conf &
/usr/local/bin/rest_api.py >/dev/null 2>&1 &
python /api.py &
/usr/bin/pixiecore api http://127.0.0.1:${HTTP_PORT} --dhcp-no-bind -p 81 &
dnsmasq
tail -f /var/log/dnsmasq.log
