---
nvidia_container_toolkit_repo_base_url: "https://nvidia.github.io/libnvidia-container"
nvidia_container_toolkit_repo_gpg_url: "{{ nvidia_container_toolkit_repo_base_url }}/gpgkey"
nvidia_container_toolkit_keyring_ascii_path: "/usr/share/keyrings/nvidia-container-toolkit-keyring.asc"
nvidia_container_toolkit_keyring_path: "/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg"
nvidia_container_toolkit_apt_source_path: "/etc/apt/sources.list.d/nvidia-container-toolkit.list"
nvidia_container_toolkit_package: "nvidia-container-toolkit"
nvidia_container_toolkit_configure_docker: true
nvidia_container_toolkit_set_as_default_runtime: true
nvidia_container_toolkit_restart_docker: true
