pipeline {
  agent any
  environment {
    DEEPOPS_FULL_INSTALL = ''
    DEEPOPS_VAGRANT_OS = 'ubuntu'
  }
  stages {
    stage('Stop Any Old Builds') {
      steps {
        milestone label: '', ordinal:  Integer.parseInt(env.BUILD_ID) - 1
        milestone label: '', ordinal:  Integer.parseInt(env.BUILD_ID)
      }
    }
    stage('Cluster Up') {
      steps {
        // TODO: ideally lock should work with declared stages
        lock(resource: null, label: 'gpu', quantity: 1, variable: 'GPUDATA') {
          echo "Reset repo and unmunge files"
          sh '''
            git reset --hard
            rm -rf config
          '''

          echo "Munge files for testing"
          sh '''
            bash -x ./.jenkins-scripts/munge-files.sh
          '''

          echo "Vagrant Up"
          sh '''
            bash -x ./.jenkins-scripts/vagrant-startup.sh
          '''

          echo "Cluster Up"
          sh '''
            bash -x ./.jenkins-scripts/test-cluster-up.sh
          '''

          echo "Verify we can run a GPU job"
          sh '''
            timeout 500 bash -x ./.jenkins-scripts/run-gpu-job.sh
          '''

          echo "Verify ingress config"
          sh '''
             bash -x ./.jenkins-scripts/verify-ingress-config.sh
          '''

          echo "Set up Slurm"
          sh '''
            bash -x ./.jenkins-scripts/test-setup-slurm.sh
          '''

          echo "Test Slurm"
          sh '''
            timeout 60 bash -x ./.jenkins-scripts/test-slurm-job.sh
          '''

          echo "Test NFS"
          sh '''
            timeout 60 bash -x ./.jenkins-scripts/test-slurm-nfs-mount.sh
          '''
        }
      }
    }
  }
  post {
    always {
      sh '''
        pwd
        cd virtual && ./vagrant_shutdown.sh
      '''
    }
  }
}
