apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-job
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
        - name: pytorch-container
          image: nvcr.io/nvidia/pytorch:26.04-py3
          command: ["/bin/sh"]
          args: ["-c", "python -c 'import torch; print(\"cuda_available=\", torch.cuda.is_available()); print(\"device_count=\", torch.cuda.device_count())'"]
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Never
