#!/usr/bin/env bash
set -ex

command -v docker >/dev/null || exit 0  # docker not installed

for id in $(docker ps -aq)
do
    {# Tell jinja not to process the double braces -#}
    {% raw -%}
    if docker inspect "$id" --format '{{.HostConfig.CgroupParent}} {{.Name}}' | grep kube
    {% endraw -%}
    then
        continue  # skip kube containers
    fi

    logger -s -t slurm-epilog "Removing docker container $id ..."

    docker stop "$id" || true
    if docker inspect "$id"
    then
        docker rm "$id"
    fi
done
