{
 "title": "GPU Nodes",
 "tags": [
  "cluster",
  "GPU"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "server",
    "query": "query_result(label_replace(DCGM_FI_DEV_POWER_USAGE{instance=~\".*:9400\"}, \"instance\", \"$1\", \"instance\", \"(.*):9400.*\"))"
   }
  ]
 },
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$hostname:9100\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "node_load5{instance=\"$hostname:9100\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "node_load15{instance=\"$hostname:9100\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "System Power Draw",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=\"$hostname:9100\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "ipmi_power_watts{instance=\"$hostname:9290\",name=\"PWR_PSU0\"}",
     "legendFormat": "PSU0"
    },
    {
     "expr": "ipmi_power_watts{instance=\"$hostname:9290\",name=\"PWR_PSU1\"}",
     "legendFormat": "PSU1"
    },
    {
     "expr": "ipmi_power_watts{instance=\"$hostname:9290\",name=\"PWR_PSU2\"}",
     "legendFormat": "PSU2"
    },
    {
     "expr": "ipmi_power_watts{instance=\"$hostname:9290\",name=\"PWR_PSU3\"}",
     "legendFormat": "PSU3"
    },
    {
     "expr": "ipmi_power_watts{instance=\"$hostname:9290\",name=\"PWR_PSU4\"}",
     "legendFormat": "PSU4"
    },
    {
     "expr": "ipmi_power_watts{instance=\"$hostname:9290\",name=\"PWR_PSU5\"}",
     "legendFormat": "PSU5"
    },
    {
     "expr": "ipmi_power_watts{instance=\"$hostname:9290\",name=\"PWR_PSU6\"}",
     "legendFormat": "PSU6"
    }
   ]
  },
  {
   "title": "Total System Power Draw",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=\"$hostname:9100\"}"
    },
    {
     "expr": "ipmi_power_watts{instance=\"$hostname:9290\",name=\"PWR_SYSTEM\"}"
    }
   ]
  },
  {
   "title": "Ethernet Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$hostname:9100\",device=~\"en.*\"}[$__interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$hostname:9100\",device=~\"en.*\"}[$__interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$hostname:9100\"} - node_memory_MemFree_bytes{instance=\"$hostname:9100\"} - node_memory_Buffers_bytes{instance=\"$hostname:9100\"} - node_memory_Cached_bytes{instance=\"$hostname:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$hostname:9100\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$hostname:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$hostname:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=\"$hostname:9400\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total GPU Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=\"$hostname:9400\"})"
    }
   ]
  },
  {
   "title": "Infiniband Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total{instance=\"$hostname:9100\"}[$__interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total{instance=\"$hostname:9100\"}[$__interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$hostname:9100\"}) - sum(node_filesystem_avail_bytes{device!=\"rootfs\",instance=\"$hostname:9100\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$hostname:9100\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$hostname:9100\"} - node_memory_MemFree_bytes{instance=\"$hostname:9100\"}  - node_memory_Buffers_bytes{instance=\"$hostname:9100\"} - node_memory_Cached_bytes{instance=\"$hostname:9100\"}) / node_memory_MemTotal_bytes{instance=\"$hostname:9100\"})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=\"$hostname:9400\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total GPU Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{instance=\"$hostname:9400\"})"
    }
   ]
  },
  {
   "title": "PCIe Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(DCGM_FI_DEV_PCIE_TX_THROUGHPUT{instance=\"$hostname:9400\"}[$__interval]))",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(rate(DCGM_FI_DEV_PCIE_RX_THROUGHPUT{instance=\"$hostname:9400\"}[$__interval]))",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$hostname:9100\"}[$__interval])",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$hostname:9100\"}[$__interval])",
     "legendFormat": "Write ({{device}})"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=\"$hostname:9100\"}[$__interval]))",
     "legendFormat": "I/O time"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "description": "GPU Shutdown Temp: 90 C\nGPU Slowdown Temp: 87 C\nGPU Max Operating Temp: 83 C",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"$hostname:9400\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Avg GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=\"$hostname:9400\"})"
    }
   ]
  },
  {
   "title": "NVLINK Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{instance=\"$hostname:9400\"}[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$hostname:9100\"}"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"$hostname:9400\"}/(DCGM_FI_DEV_FB_USED{instance=\"$hostname:9400\"}+DCGM_FI_DEV_FB_FREE{instance=\"$hostname:9400\"})*100",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total GPU Mem Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(DCGM_FI_DEV_FB_USED{instance=\"$hostname:9400\"}/(DCGM_FI_DEV_FB_USED{instance=\"$hostname:9400\"}+DCGM_FI_DEV_FB_FREE{instance=\"$hostname:9400\"})*100*10))/10"
    }
   ]
  },
  {
   "title": "GPU Mem Cpy Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{instance=\"$hostname:9400\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_SM_CLOCK{instance=\"$hostname:9400\"}*1000000)"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_CLOCK{instance=\"$hostname:9400\"}*1000000)"
    }
   ]
  }
 ]
}