{
 "title": "SLURM Dashboard",
 "tags": [ "cluster" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPUs",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_cpus_total", "legendFormat": "Total" },
    { "expr": "slurm_cpus_alloc", "legendFormat": "Allocated" },
    { "expr": "slurm_cpus_idle", "legendFormat": "Idle" }
   ]
  },
  {
   "title": "GPUs",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_gpus_total", "legendFormat": "Total" },
    { "expr": "slurm_gpus_alloc", "legendFormat": "Allocated" },
    { "expr": "slurm_gpus_idle", "legendFormat": "Idle" }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_nodes_alloc", "legendFormat": "Allocated" },
    { "expr": "slurm_nodes_comp", "legendFormat": "Completing" },
    { "expr": "slurm_nodes_idle", "legendFormat": "Idle" },
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_down + slurm_nodes_drain + slurm_nodes_idle + slurm_nodes_mix + slurm_nodes_comp + slurm_nodes_maint",
     "legendFormat": "Total"
    },
    { "expr": "-slurm_nodes_down", "legendFormat": "Down" },
    { "expr": "-slurm_nodes_drain", "legendFormat": "Drain" },
    { "expr": "-slurm_nodes_err", "legendFormat": "In *error* state" },
    { "expr": "-slurm_nodes_fail", "legendFormat": "In *fail* state" },
    { "expr": "-slurm_nodes_maint", "legendFormat": "In *maintenance* state" }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_queue_completing", "legendFormat": "Completing" },
    { "expr": "slurm_queue_running", "legendFormat": "Running" },
    { "expr": "slurm_queue_pending", "legendFormat": "Pending" },
    { "expr": "slurm_queue_completed", "legendFormat": "Completed" },
    { "expr": "-slurm_queue_cancelled", "legendFormat": "Canceled" },
    { "expr": "-slurm_queue_timeout", "legendFormat": "Timed out" },
    { "expr": "-slurm_queue_failed", "legendFormat": "Failed" },
    { "expr": "-slurm_queue_node_fail", "legendFormat": "Node failed" },
    { "expr": "-slurm_queue_suspended", "legendFormat": "Suspended" },
    { "expr": "-slurm_queue_preempted", "legendFormat": "Preempted" }
   ]
  },
  {
   "title": "Slurm Scheduler Threads",
   "type": "stat",
   "description": "The number of current active slurmctld threads.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "slurm_scheduler_threads", "legendFormat": "Slurm Scheduler Threads" }
   ]
  },
  {
   "title": "Agent Queue Size",
   "type": "stat",
   "description": "The agent mechanism helps to control communication between the Slrum daemons and the controller for a best effort.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "slurm_scheduler_queue_size", "legendFormat": "Agent Queue Size" }
   ]
  },
  {
   "title": "Backfill Scheduler Cycles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "slurm_scheduler_backfill_last_cycle",
     "legendFormat": "Scheduler Backfill Last Cycle"
    },
    {
     "expr": "slurm_scheduler_backfill_mean_cycle",
     "legendFormat": "Scheduler Backfill Mean Cycle"
    }
   ]
  },
  {
   "title": "Scheduler Backfill Depth Mean",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_scheduler_backfill_depth_mean",
     "legendFormat": "Mean of processed jobs during backfilling scheduling cycles"
    }
   ]
  },
  {
   "title": "Scheduler Cycles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "slurm_scheduler_last_cycle", "legendFormat": "Scheduler Last Cycle Time" },
    { "expr": "slurm_scheduler_mean_cycle", "legendFormat": "Scheduler Mean Cycle Time" }
   ]
  }
 ]
}