#!/usr/bin/env bash
set -ex

command -v enroot >/dev/null || exit 0  # enroot not installed

{% if enroot_runtime_path | default(none) %}
runtime_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "{{ enroot_runtime_path }}"')"
mkdir -p "$runtime_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$runtime_path"
chmod 0755 "$(dirname $runtime_path)"
chmod 0700 "$runtime_path"
{% endif %}

{% if enroot_cache_path | default(none) %}
cache_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "{{ enroot_cache_path }}"')"
mkdir -p "$cache_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$cache_path"
chmod 0770 "$cache_path"
{% endif %}

{% if enroot_data_path | default(none) %}
data_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "{{ enroot_data_path }}"')"
mkdir -p "$data_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$data_path"
chmod 0700 "$data_path"
{% endif %}
